sonata_admin:
    title: 'Billing Project'
    title_logo: /images/mvK7y08y_400x400.jpg
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    templates:
        user_block: '@SonataAdmin/Core/user_block.html.twig'
        show: "@App/Admin/display_customer.html.twig"
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
